name: Frontend React

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Public IP
      id: ip
      uses: haythem/public-ip@v1.2
    - name: Get latest code
      uses: actions/checkout@v2.3.2
    - name: Turnstyle
      uses: softprops/turnstyle@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Use Node.js 15.x
      uses: actions/setup-node@v2
      with:
        node-version: 15.x
    - name: Install packages
      run: yarn install
    - name: Build app
      run: yarn build
    - name: FTP publish
      uses: sebastianpopp/ftp-action@releases/v2
      with:
        host: ${{ secrets.FTP_HOST }}
        user: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        remoteDir: ${{ secrets.FTP_DIR }}
        localDir: build/
        options: "-v --delete"
